#package radseq;



###################################################################################################################################
#
# Copyright 2014 IRD-CIRAD
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/> or
# write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
# You should have received a copy of the CeCILL-C license with this program.
#If not see <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.txt>
#
# Intellectual property belongs to IRD, CIRAD and South Green developpement plateform
# Written by Cecile Monat, Christine Tranchant, Ayite Kougbeadjo, Cedric Farcy, Mawusse Agbessi, Marilyne Summo, and Francois Sabot
#
###################################################################################################################################



use strict;
use warnings;
use Data::Dumper;

use lib qw(.);
use localConfig;
use toolbox;


################################################################################################
# sub radseq::parseKeyFile => to parse radseq keyfile in
################################################################################################
# arguments :
# 	- fileIn : the Keyfile file to split
#	- dirOut : the directory that contains all the files generated by radseq::splitKeyFile (barecode files)
################################################################################################
# return boolean :
#	- 1 if radseq::splitKeyFile has runned correctly
#	- else 0
################################################################################################

sub splitKeyFile
{
	#toolbox::exportLog("ERROR: radseq::splitKeyFile : should get at least two arguments\n",0) if (@_ < 2);
	my ($keyFileFile,$dirOut,$optionsHachees)=@_;

	#toolbox::exportLog("INFOS: radseq::splitKeyFile : running\n", 1);
	my $options="";
		if ($optionsHachees)
	{
		$options=toolbox::extractOptions($optionsHachees);		##Get given options
	}

	my $comp=0;
	my @head;

	open(KEYFILE, "<", $keyFileFile) or die  $!;# toolbox::exportLog("ERROR: radseq::splitKeyFile : Can't open the file $keyFileFile $!\n",0);

	#Reading keyfile input
	while (<KEYFILE>)				# for each line of the keyfile
	{
		my $line = $_;			# read line
		chomp $line;
		if ( $comp == 0 )		#Open KeyFile and check if 4 first column is "Flowcell	Lane	Barcode	DNASample" then split on barecode
		{
			@head = split("\t",$line,5);
			if ($head[0] ne "Flowcell" or $head[1] ne "Lane" or $head[2] ne "Barcode" or $head[3] ne "DNASample")
			{
				#toolbox::exportLog("ERROR: radseq::splitKeyFile : The Keyfile header of file $keyFileFile is not like 'Flowcell\tLane\tBarcode\tDNASample' '$! \n",0);
				print "ERROR: radseq::splitKeyFile : The Keyfile header of file $keyFileFile is not like 'Flowcell\tLane\tBarcode\tDNASample' \n";
				exit;
			}
			$comp+=1;
		}
		else					# If header is good split and open barecode file for lane
		{
			$comp+=1;
			##DEBUG print $line."\n";
			my ($flowcell, $lane, $barcode, $DNASample, $other) = split("\t",$line,5) ;
			##DEBUG print $DNASample."\n";
			if ($DNASample =~ m/.*\..*/ )	# change "." to "_" for runnig radseq::process_radtags
			{
				$DNASample =~ s/\./_/;
			}
			if ($lane !~ m/^\d+$/ )	# Test if lane is not numeric
			{
				#toolbox::exportLog("ERROR: radseq::splitKeyFile : The Keyfile lane "$lane" on line $comp is not numeric for file $keyFileFile '$! \n",0);
				print "ERROR: radseq::splitKeyFile : The Keyfile lane '$lane' on line $comp is not numeric for file $keyFileFile \n";
				exit;
			}

			my $outputFileName =$dirOut."/"."barcode_run01_lane$lane.txt";
			##DEBUG print $outputFileName."\n";
			open(LANEFILE, ">>",$outputFileName) or die $!; #toolbox::exportLog("ERROR: radseq::splitKeyFile : Can't open the file $outputFileName $!\n",0);
			print LANEFILE $barcode."\t".$DNASample."\n";
		}
	}
}

##DEBUG
splitKeyFile("../DATA-TEST/radseq/keyFileTest.txt", "../DATA-TEST/radseq/barecode")


#################################################################################################
## END sub radseq::splitKeyFile
#################################################################################################

#1;

#=head1 NOM

#package I<radseq>

#=head1 SYNOPSIS

	#use radseq;

	#radseq::splitKeyFile($keyFileFile,$radseqDir);


#=head1 DESCRIPTION

#This module is a set of functions related to radseq software, L<http://catchenlab.life.illinois.edu/stacks/comp/process_radtags.php>


#=head2 Functions


#=head3 splitKeyFile()

#This function split the Keyfile file on the different lane and take them in a directory (that contains the files to run radseq::process_radtags) created
#and check if "DNASample" don't contain "."'.
#2 arguments are required : the Keyfile filename and the output directory name created.

#Return 1 if radseq::splitKeyFile has ran correctly else 0.

#Example :
#C<radseq::splitKeyFile($keyFileFile,$radseqDir);>


#=head1 AUTHORS

 #Cecile Monat, Ayite Kougbeadjo, Marilyne Summo, Cedric Farcy, Mawusse Agbessi, Christine Tranchant and Francois Sabot

#L<http://www.southgreen.fr/>

#=cut
